# Generated by Django 3.2.9 on 2021-12-10 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='000-0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_entry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 18, 31, 31, 708290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
