# Generated by Django 3.2.9 on 2021-12-10 19:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0002_auto_20211211_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_entry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 19, 12, 59, 787729, tzinfo=utc)),
        ),
    ]
