# Generated by Django 3.2.9 on 2021-12-10 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0003_alter_product_date_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_entry',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 19, 20, 38, 712197, tzinfo=utc)),
        ),
    ]
